export const SET_RIDE_DETAILS = "SET_RIDE_DETAILS";
export const UPDATE_RIDE_DETAILS = "UPDATE_RIDE_DETAILS";
export const DELETE_RIDE_DETAILS = "DELETE_RIDE_DETAILS";
export const UPDATE_RIDE_STATUS = "UPDATE_RIDE_STATUS";
export const UPDATE_RIDE_LOCATION = "UPDATE_RIDE_LOCATION";
export const UPDATE_RIDE_DRIVER_INFO = "UPDATE_RIDE_DRIVER_INFO";
